### ISSUE TITLE
Simplify JSON serialization

### ISSUE THREAD

**Issue by k0001** [k0001/safe-money#10]
In our JSON serialization, we don't' really need that first `"Dense"` or `"Discrete"` value.

```
> Data.Aeson.encode (32 :: Dense "EUR")
"[\"Dense\",\"EUR\",32,1]"
> Data.Aeson.encode (4 :: Discrete "XAU" "gram")
"[\"Discrete\",\"XAU\",31103477,1000000,4]"
```

This change is backwards incompatible.

**Comment by k0001** [comment]
@ocharles since other than me, you are the only user of `safe-money` I know of: Do you mind if I do this? Are you storing raw JSON serializations somewhere?

**Comment by ocharles** [comment]
Can you elaborate on the change? I'm not entirely understanding what's
changed. I'll check out code base

**Comment by k0001** [comment]
@ocharles see the JSON serializations above as arrays? I am planning to drop the first element from both of them (i.e. the strings "Dense" and "Discrete", since it's not really necessary and makes the JSON bigger.

**Comment by k0001** [comment]
To clarify: This change will only affect you if you are storing the current JSON serialization somewhere.

**Comment by ocharles** [comment]
I've only had a cursory glance, but from the looks of things - yes, we do use the `FromJSON Dense` instance. @rehno-lindeque, @HanStolpo wrote the code using it though, so I'm CCing them.

**Comment by k0001** [comment]
@ocharles it's OK if you use the `FromJSON` instance for ephemeral data that exists while the app is running. The problem would only arise if you were *storing* the generated JSON somewhere for later retrieval and expecting to be able to decode it at a later date.

But actually, I just had an idea: I'll make the `FromJSON` implementation support both the new format and the old format, while having the `ToJSON` instance generate only the new format. So... don't worry about a thing :)

**Comment by ocharles** [comment]
> The problem would only arise if you were storing the generated JSON somewhere for later retrieval and expecting to be able to decode it at a later date.

Well, and any external clients that expect to be able to communicate with this Haskell application. Our Elm app posts to the Haskell application, so we would have to remember to update its JSON encoding.

I don't think we use `ToJSON` anywhere, so that would work for us.

**Comment by k0001** [comment]
@ocharles I just made the change here https://github.com/k0001/safe-money/commit/89156d445cbca7d7c5b370cc896f5333a684014a

Agreed, if your client app is relying on the current `ToJSON` behavior, it'll need to change a bit. Sorry :(

**Comment by rehno-lindeque** [comment]
Thanks for the heads up @k0001!
