### ISSUE TITLE
Category ExchangeRate?

### ISSUE THREAD

**Issue by ocharles** [k0001/safe-money#15]
Haven't actually checked if it makes sense, but it seems like it should. The identity exchange just gives you back whatever you give it (1:1), and composing exchange rates takes you through multiple exchanges.

**Comment by k0001** [comment]
@ocharles excellent idea! Fixed in https://github.com/k0001/safe-money/commit/dcf31690c973c9b3f8560a5bbe516085ff62eaa5 

Thanks!!!
