### ISSUE TITLE
Reasoning behind non-infinite Dense amount?

### ISSUE THREAD

**Issue by runeksvendsen** [k0001/safe-money#16]
Hi there,

I'm curious about what the reasoning is behind not allowing a `Dense` amount that is infinite. The reason I ask is because I have a use case for it. 

I have a data type which uses `safe-money` to describe an order -- that is, a willingness to purchase a given quantity at a given price:

```haskell
data Order (base :: Symbol) (quote :: Symbol) = Order
   { oQuantity :: Money.Dense base
   , oPrice    :: Money.ExchangeRate base quote
   }
```

I would like to be able to compose orders, but in the `Category` instance of `Order` I can't define the identity `Order`, since this order needs infinite volume in order to not affect the order it's being composed with.

I haven't really played with `Category` definitions before, but I see now how it can be useful in increasing simplicity. Here's my attempt at defining the instance for `Order`, and as far as I can see I need an infinite quantity.

```haskell
import qualified Control.Category   as Cat

instance Cat.Category Order where
   id = Order (fromRational infinity) Cat.id
   o1 . o2 = Order (fromRational minQty) (oPrice o1 Cat.. oPrice o2)
      where minQty = min (toRational $ oQuantity o1) (toRational $ oQuantity o2)
```

So, for example, if we have `o1 = Order "EUR" "USD"` of quantity 1 and price 1.20, and `o2 = Order "USD" "GBP"` of quantity 2 and price 0.5, the composition `o2 . o1` should be able to exchange 1 EUR into 0.6 GBP (1.20*0.5).

**Comment by k0001** [comment]
@runeksvendsen you can't really do much with `infinity`:

```haskell
> import GHC.Real 
> infinity * 2
*** Exception: Ratio has zero denominator
> infinity - infinity
*** Exception: Ratio has zero denominator
> infinity + 5
*** Exception: Ratio has zero denominator
```

Another thing to consider is that an order for an infinite amount can't ever be satisfied (as in: there's no infinite money in existence).

It sounds like `Category` might not be what you want.

**Comment by k0001** [comment]
Perhaps you want to try something like this?

```haskell
exchangeThrough :: ExchangeRate b c -> Order a b -> Order b c
exchangeThrough xbc (Order da xab) = Order (exchange xab da) xbc
```

Also, I'd think that you'd want `Discrete` amounts for placing orders unless something like an order for “one third of a dollar” is possible (i.e., 0.33333333…). I might be wrong, but it seems reasonable to desire discrete amounts for orders.

**Comment by k0001** [comment]
Or maybe something like this, which is more closely related to the `Category` composition.

```haskell
exchangeThrough' :: ExchangeRate b c -> Order a b -> Order a c
exchangeThrough' xbc (Order da xab) = Order da (xbc Cat.. xab)
```

**Comment by sellout** [comment]
I thought you _could_ define an infinite `Dense` via `fromRational`. This way you can have your identity value, but also use `mkDense` guarantee non-infinite values where you don’t expect them.

**Comment by k0001** [comment]
Yes, you can use `fromRational`, but... I'm not sure how good that will be in practice, seeing as how `infinity` leads to the “ratio has zero denominator” exception with most operations you attempt on it. Essentially, bottom would be part of your `id` definition.

**Comment by runeksvendsen** [comment]
On further thought, what I *really* want to do is define a *list* of orders as a category. The only reason I started with defining the category of a single `Order` was that it seemed like a reasonable starting point, but I will never use the definition for a single order.

So I think the solution is to only define the category for a *list* of orders, and define the identity “order list” to be `[order..] where order = Order (fromRational 1) Cat.id` — that is, a infinite list of orders with price 1 and quantity 1. This should work if I define the composition of two order lists in a sufficiently intelligent way.

**Comment by k0001** [comment]
@runeksvendsen that sounds reasonable.  I'm going to close this issue for the time being, but please feel free to bounce other ideas you might have :)
