### ISSUE TITLE
vector-space instances

### ISSUE THREAD

**Issue by mithrandi** [k0001/safe-money#17]
I have these orphan instances currently defined in my project:

```haskell
import Data.AdditiveGroup
import Data.VectorSpace
import Money

instance AdditiveGroup (Dense currency)

instance GoodScale scale => AdditiveGroup (Discrete' currency scale)

instance VectorSpace (Dense currency)

instance GoodScale scale => VectorSpace (Discrete' currency scale)
```

Do you think it would make sense to include them in safe-money? These instances allow avoiding some of the problematic operators from `Num`; eg. `(*) :: Dense c -> Dense c -> Dense c` doesn't actually make sense, but `(^*) :: Dense c -> Rational -> Dense c` does.

**Comment by k0001** [comment]
Thanks for this suggestion, @mithrandi.

I'm not familiar with the `vector-space` library myself, but one thing that worries me is how the instances would deal with `GHC.Real.infinity :: Rational` and `GHC.Real.notANumber :: Rational`. Do you have some thoughts about that?

I think it would be nice to offer this instance right from `safe-money`, yes. However, we should make it optional through some Cabal flag in case users want to avoid the extra dependency on `vector-space`). Take a look at how we are currently doing this here: https://github.com/k0001/safe-money/blob/a3c208ff781ba1ebd30bcd4c09113230d990c3be/safe-money.cabal#L91-L93

**Comment by mithrandi** [comment]
Aha, the flag approach looks good. I'll look into what happens with infinity / NaN with the default instance implementations, we might need to write out the instance bodies (but they're not hard to write once the desired behaviour has been figured out).

**Comment by k0001** [comment]
Related: #21

**Comment by k0001** [comment]
@mithrandi this has been implemented now :)
