### ISSUE TITLE
No obvious way to go from String to Dense/Discrete back to String

### ISSUE THREAD

**Issue by wilfreddenton** [k0001/safe-money#18]
The APIs that I use all return decimal numbers as `String`s i.e. "1.24". It would be great if there was a convenient and safe way to convert these values to a `Dense`/`Discrete` and back.

Here's a way I've got to go from `String` to `Discrete`
```
...
case readSigned readFloat myNumberString of
  [(d, _)] -> fromIntegral $ truncate $ d * 100 :: Discrete "USD" "cent"
  _ -> ...
```

Not sure how to get back to `String` though.

**Comment by k0001** [comment]
@wilfreddenton sorry about the delayed reply, somehow I didn't notice this issue before in my inbox.

I think you are right, it would be useful if `safe-money` could provide such helper functions if possible. However, I'm a bit undecided about whether these should work on `String` or `Text`.

**Comment by k0001** [comment]
This highlighted a potential issue when parsing these values (see #19)

**Comment by wilfreddenton** [comment]
@k0001 I would lean towards using `Text`. One specific reason is that the `String` type in `Data.Aeson` wraps a `Text` value. Also it seems that many people in the Haskell community prefer `Text` over `String` for human readable strings ([Text or String](https://www.reddit.com/r/haskell/comments/3rrlih/text_or_string/).

**Comment by k0001** [comment]
I'm going to stay with `String` for the time being, seeing how much of the other textual things the library exports are `String` (e.g., currency names). I might change it in the future if the performance is significantly different, but I have my doubts about that, seeing how the strings are particularly short.

**Comment by k0001** [comment]
Please feel free to open a different ticket if you think supporting `Text` is important. I'll be happy to make the change then.

**Comment by wilfreddenton** [comment]
These methods look good. They're going to be very useful for me and others I'm sure. Thanks for implementing them! My only complaint is that the large number of arguments that `denseToDecimal` takes is a bit of an eye sore but I see the need for them.

I think using `String` is fine. It's simple enough to `pack` and `unpack` them.

**Comment by k0001** [comment]
@wilfreddenton I'm happy to hear that.

Yes, my hope is that users of this function, once they figure out the settings they want, will wrap them in some other function. 


```haskell
newtype RenderedMoney = UnsafeRenderedMoney String

renderMoneyDense :: Money.Approximation -> Money.Dense currency -> RenderedMoney
renderMoneyDense a dns = UnsafeRenderedMoney  $ 
   let dec = Money.denseToDecimal a True (Just ',') '.' 2 (Proxy :: Proxy '(1,1)) dns
   in Money.denseCurrency x <> " " <> dec
```

**Comment by k0001** [comment]
I just realized: Since `denseToDecimal` already returns a `Maybe`, it could take a `Rational` instead of a `Proxy scale`. Hmmm. I added the `Maybe` return type later on and forgot to change that. Arghh... OK, I'll change it and upload a new version soon.
