### ISSUE TITLE
Parameterize "Dense" and "ExchangeRate" over underlying number type

### ISSUE THREAD

**Issue by runeksvendsen** [k0001/safe-money#38]
Using `Rational` as the underlying number type for e.g. `ExchangeRate` gives us absolute precision, at the cost of performance. `Rational` becomes increasingly slow after the numerator and denominator no longer fit in a 64 bit integer. Being able to switch out this `Rational` with e.g. a `Double` would give us more performance, at the cost of precision. There are several scenarios where this is desirable.

Practically, this could be done by exporting `data Dense' num (currency :: Symbol)` and `data ExchangeRate' num (src :: Symbol) (dst :: Symbol)` from a different module (to maintain backwards compatibility), define all operations on them through type class constraints (e.g. requiring `Num num` for multiplication of exchange rates), and then exporting e.g. `type Dense = Dense' Rational` from `Money`.

The `Dense` and `ExchangeRate` types are useful regardless of the precision of the underlying number type, since they prevent us from mixing up our monetary units when, e.g., multiplying two exchange rates.

**Comment by k0001** [comment]
@runeksvendsen I don't particularly like the idea of there being a possibility of using the `safe-money` vocabulary to construct an imprecise monetary value, even if accidentally. The approach you propose would certainly work, but it would deviate the library from its goal. Moreover, as an unintended side effect, type inference would become quite poor. I think having the user explicitly convert to a less precise type of his own choice if necessary is better. 

Are you frequently encountering situations where the numerator or denumerator exceed 64 bits? If that's the case, maybe the underlying `Rational` is not being normalized as often as it should?

**Comment by k0001** [comment]
I'm closing this, as I don't think it aligns with `safe-money`'s goals. Please let me know if there are particular cases you would like to address.
