### ISSUE TITLE
Dynamic currencies?

### ISSUE THREAD

**Issue by ssadler** [k0001/safe-money#49]
Is this library suitable for use when you don't know what currency a value will represent at compile time? It's not clear to me since the currency symbol is in the type.

For example if I am an exchange I may wish to have a list of currency pairs, and be able to dispatch conversions for each of them using the same code. Is safe-money suitable in this circumstance?

**Comment by k0001** [comment]
Hello @ssaddler

Yes,definitely, that's what all the data types

**Comment by k0001** [comment]
Hello @ssaddler

Yes, definitely, that's what all the datatypes prefixed with 'Some' are for. There's a a lot of machinery for working with them :)

While a bit outdated, you may enjoy reading https://ren.zone/articles/safe-money which talks in great detail about what it means to deal with currencies dynamically, as you say.

**Comment by k0001** [comment]
Hello @ssaddler

Yes, definitely, that's what all the datatypes prefixed with 'Some' are for. There's a a lot of machinery for working with them :)

While a bit outdated, you may enjoy reading https://ren.zone/articles/safe-money which talks in great detail about what it means to deal with currencies dynamically, as you say.

**Comment by ssadler** [comment]
That's great, thanks for the explanation! I'll close this issue now.
