### ISSUE TITLE
Cannot build with store-0.4.

### ISSUE THREAD

**Issue by ocharles** [k0001/safe-money#5]

**Comment by k0001** [comment]
@ocharles Thanks, I'll fix this. Meanwhile, you can disable building the `store` instances and the `store` dependency with the `-f-store` cabal flag.

**Comment by k0001** [comment]
Hey @ocharles I couldn't reproduce this. 

By the way, I did a lot of breaking changes in `master` just now. Can you take a look at the [`changelog.md`](https://github.com/k0001/safe-money/blob/master/changelog.md) file to see what's coming on `HEAD`? (Mostly I just moved things around, but it's very likely that you were using the `mkXxxRep` functions, and I renamed those to `fromRawXxxRep`). I won't push this up to Hackage until you acknowledge this changelog so as to not break your stuff.

**Comment by k0001** [comment]
@ocharles FWIW, `nix-build release.nix -A ghc802_safe-money` works just fine even after uncommenting that line mentioning `store-0.4`. That's how I tested this with `store-0.4`.

**Comment by k0001** [comment]
@ocharles FWIW, I just pushed this up to Hackage.

**Comment by ocharles** [comment]
Thanks Renzo. I only encountered this due to some Stack snapshot.
