### ISSUE TITLE
safe-money-aeson: pattern match error 

### ISSUE THREAD

**Issue by codygman** [k0001/safe-money#53]
Possibly related to #10.

Here's an example:

```haskell
Prelude Money Money.Aeson Text Aeson LBS Data.Text.Lazy.Encoding TLE> Aeson.eitherDecode @(Dense "USD") "[\"0\",\"0\",0,0]"
Left "Error in $: Pattern match failure in do expression at src/Money/Aeson.hs:64:8-35"
```

I'm using safe-money 0.9 from stackage lts-15.0.

**Comment by k0001** [comment]
Hey @codygman, that's not a valid JSON encoding for a `Dense` value. Check the [tests](https://github.com/k0001/safe-money/blob/07f862a807c734e0eefba877e7fbaee6982c5023/safe-money-aeson/test/Main.hs#L225-L230) or the [haddocks](https://hackage.haskell.org/package/safe-money-aeson-0.1.1/docs/Money-Aeson.html) for some examples.
